### ISSUE TITLE
Unexpected Error (13) following HelloWorld tutorial

### ISSUE THREAD

**Issue by mitchazj** [GoogleCloudPlatform/google-cloud-visualstudio#763]
Been following the [quickstart tutorial](https://cloud.google.com/appengine/docs/flexible/dotnet/quickstart) for .NET core and getting the following error output using `--verbosity=debug`:

```
DEBUG: Converted YAML to JSON: "{
  "betaSettings": {
    "module_yaml_path": "app.yaml",
    "vm_runtime": "aspnetcore"
  },
  "env": "flex",
  "handlers": [
    {
      "script": {
        "scriptPath": "PLACEHOLDER"
      },
      "urlRegex": ".*"
    }
  ],
  "runtime": "vm"
}"
DEBUG: Received operation: [apps/memes-aspnetcore/operations/b8a669ed-8a7a-429f-ae09-51670297e4d3]
DEBUG: Operation [apps/memes-aspnetcore/operations/b8a669ed-8a7a-429f-ae09-51670297e4d3] not complete. Waiting to retry.
Updating service [default].../DEBUG: Operation [apps/memes-aspnetcore/operations/b8a669ed-8a7a-429f-ae09-51670297e4d3] not complete. Waiting to retry.
Updating service [default]...|DEBUG: Operation [apps/memes-aspnetcore/operations/b8a669ed-8a7a-429f-ae09-51670297e4d3] not complete. Waiting to retry.
Updating service [default]...\DEBUG: Operation [apps/memes-aspnetcore/operations/b8a669ed-8a7a-429f-ae09-51670297e4d3] not complete. Waiting to retry.
Updating service [default].../DEBUG: Operation [apps/memes-aspnetcore/operations/b8a669ed-8a7a-429f-ae09-51670297e4d3] complete. Result: {
    "metadata": {
        "target": "apps/memes-aspnetcore/services/default/versions/20170723t142901",
        "method": "google.appengine.v1.Versions.CreateVersion",
        "user": "<censored>",
        "insertTime": "2017-07-23T04:30:27.362Z",
        "ephemeralMessage": "Provisioning instances to serve application.",
        "@type": "type.googleapis.com/google.appengine.v1.OperationMetadataV1"
    },
    "done": true,
    "name": "apps/memes-aspnetcore/operations/b8a669ed-8a7a-429f-ae09-51670297e4d3",
    "error": {
        "message": "Unexpected Error. ()",
        "code": 13
    }
}
Updating service [default]...failed.
DEBUG: (gcloud.beta.app.deploy) Error Response: [13] Unexpected Error. ()
Traceback (most recent call last):
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\cli.py", line 797, in Execute
    resources = args.calliope_command.Run(cli=self, args=args)
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\backend.py", line 871, in Run
    resources = command_instance.Run(args)
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\surface\app\deploy.py", line 81, in Run
    check_for_stopped=True
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\command_lib\app\deploy_util.py", line
   414, in RunDeploy
    args.image_url, all_services, app.gcrDomain)
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\command_lib\app\deploy_util.py", line
 248, in Deploy
    endpoints_info)
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\app\appengine_api_client.py",
 line 156, in DeployService
    message=message)
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\app\operations_util.py", line
 206, in WaitForOperation
    sleep_ms=retry_interval)
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\util\waiter.py", line 266, in
 WaitFor
    sleep_ms=sleep_ms)
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\util\retry.py", line 222, in RetryOnResult
    if not should_retry(result, state):
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\util\waiter.py", line 260, in _IsNotDone
    return not poller.IsDone(operation)
  File "C:\Users\mitch\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\app\operations_util.py", line
 131, in IsDone
    encoding.MessageToPyValue(operation.error)))
OperationError: Error Response: [13] Unexpected Error. ()
ERROR: (gcloud.beta.app.deploy) Error Response: [13] Unexpected Error. ()
```
Is this beta pains, or am I doing something stupid? I'm using the latest releases.

**Comment by mitchazj** [comment]
The app publishes, but returns a 500 server error: https://memes-aspnetcore.appspot.com/

**Comment by ivannaranjo** [comment]
Hello, sorry for the late response. That seems like a transient error during the deployment of the app to Flex. If you can, try it again. Let us know if you have more issues.

**Comment by aug70** [comment]
This is not a transient error. I'm constantly getting the same error while trying to deploy.

* [Stackoverflow question ](https://stackoverflow.com/questions/46059583/gcloud-app-deploy-error-response-13-unexpected-error)
* [Tutorial that cause this](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..%2Findex#0)

```
DEBUG: Operation [apps/yalimaytul-com/operations/80508f16-faa3-4059-b61a-c79370a0a394] complete. Result: {
    "metadata": {
        "target": "apps/yalimaytul-com/services/default/versions/gcp", 
        "method": "google.appengine.v1.Versions.CreateVersion", 
        "user": "yalim.aytul@gmail.com", 
        "insertTime": "2017-09-06T20:11:22.966Z", 
        "ephemeralMessage": "Provisioning instances to serve application.", 
        "endTime": "2017-09-06T20:11:39.304Z", 
        "@type": "type.googleapis.com/google.appengine.v1.OperationMetadataV1"
    }, 
    "done": true, 
    "name": "apps/yalimaytul-com/operations/80508f16-faa3-4059-b61a-c79370a0a394", 
    "error": {
        "message": "Unexpected Error. ()", 
        "code": 13
    }
}
failed.
DEBUG: (gcloud.app.deploy) Error Response: [13] Unexpected Error. ()
Traceback (most recent call last):
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 789, in Execute
    resources = args.calliope_command.Run(cli=self, args=args)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 754, in Run
    resources = command_instance.Run(args)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/surface/app/deploy.py", line 64, in Run
    parallel_build=False)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 611, in RunDeploy
    flex_image_build_option=flex_image_build_option)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 410, in Deploy
    endpoints_info)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_api_client.py", line 171, in DeployService
    message=message)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/operations_util.py", line 206, in WaitForOperation
    sleep_ms=retry_interval)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 266, in WaitFor
    sleep_ms=sleep_ms)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 222, in RetryOnResult
    if not should_retry(result, state):
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 260, in _IsNotDone
    return not poller.IsDone(operation)
  File "/Users/yaytul/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/operations_util.py", line 131, in IsDone
    encoding.MessageToPyValue(operation.error)))
OperationError: Error Response: [13] Unexpected Error. ()
ERROR: (gcloud.app.deploy) Error Response: [13] Unexpected Error. ()
```

**Comment by jamesarosen** [comment]
GoogleCloudPlatform/getting-started-java#281 suggests
```sh
$ gcloud config set app/use_deprecated_preparation True
```
though @jabubake says there,

> Hi if you are using the latest gcloud version you should n't need this workaround.

I'm using the latest `gcloud` and I get error 13 with or without the `app/use_deprecated_preparation` setting.
